BASE_TASK_CONFIG_PATH: "configs/tasks/vln_r2r.yaml"
TRAINER_NAME: "dagger"
RUN_NAME: debug
ENV_NAME: "VLNILEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
TENSORBOARD_DIR: tensorboard_dirs/debug
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/checkpoints/vln/debug"

EVAL_CKPT_PATH_DIR: "data/checkpoints/vln/debug"  # if file, eval just that checkpoint.
VIDEO_OPTION: []  # ["disk", "tensorboard"]
VIDEO_DIR: "videos/debug"
EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_seen

DAGGER:
  LR: 2.5e-4
  STABBINGS: 10
  EPOCHS: 6
  UPDATE_SIZE: 5000
  BATCH_SIZE: 1
  P: 0.75
  USE_IW: True
  LMDB_MAP_SIZE: 1.1e+12  # ~1TB (in bytes)

RL:
  VLN:
    # Vision and Language Navigation parameters
    INSTRUCTION_ENCODER:
      vocab_size: 2504
      max_length: 153
      use_pretrained_embeddings: True
      embedding_file: "./data/datasets/vln/mp3d/r2r/v1/preprocessed/embeddings.json"
      dataset_vocab: "./data/datasets/vln/mp3d/r2r/v1/preprocessed/train/train.json.gz"
      fine_tune_embeddings: False
      embedding_size: 50
      hidden_size: 128
      rnn_type: "LSTM"
    DEPTH_ENCODER:
      cnn_type: "VlnResnetDepthEncoder"  # SimpleDepthCNN or VlnResnetDepthEncoder
      output_size: 128
      backbone: "resnet50"
      ddppo_checkpoint: "data/dd-ppo-weights/gibson-2plus-resnet50.pth"
    VISUAL_ENCODER:
      cnn_type: "ResNet50"
      output_size: 256
      activation: "relu"
    STATE_ENCODER:
      hidden_size: 512
      rnn_type: "GRU"  # Currently only works with GRU
