BASE_TASK_CONFIG_PATH: "configs/tasks/vln_r2r.yaml"
TRAINER_NAME: "imitation_vln"
ENV_NAME: "VLNILEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 1
VIDEO_OPTION: ["disk", "tensorboard"]
TENSORBOARD_DIR: tensorboard_dirs/debug/debug
VIDEO_DIR: "videos/debug"
# TEST_EPISODE_COUNT: 10
EVAL_CKPT_PATH_DIR: "data/checkpoints/vln/debug/debug"
NUM_PROCESSES: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/checkpoints/vln/debug/debug"
NUM_UPDATES: 1000000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 100
EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: train

IL:
  GT_PATH: "data/datasets/vln/mp3d/r2r/v1/preprocessed/{split}/{split}_gt_all.json.gz"
  BATCH_SIZE: 128
  lr: 2.5e-4
  eps: 1e-5
  window_accuracy_size: 500

RL:
  VLN:
    # Vision and Language Navigation parameters
    INSTRUCTION_ENCODER:
      vocab_size: 2504
      max_length: 153
      use_pretrained_embeddings: True
      embedding_file: "./data/datasets/vln/mp3d/r2r/v1/preprocessed/embeddings.json"
      dataset_vocab: "./data/datasets/vln/mp3d/r2r/v1/preprocessed/train/train.json.gz"
      fine_tune_embeddings: False
      embedding_size: 50
      hidden_size: 256
      rnn_type: "LSTM"
    DEPTH_ENCODER:
      cnn_type: "SimpleDepthCNN"
      output_size: 512
    VISUAL_ENCODER:
      cnn_type: "ResNet50"
      output_size: 512
    STATE_ENCODER:
      hidden_size: 512
      rnn_type: "GRU"  # Currently only works with GRU
